// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace SpikeLaunch
{
public static class GPGSIds
{
        public const string achievement_knockoff = "CgkIqPj-8swdEAIQDA"; // <GPGSID>
        public const string achievement_take_a_dive = "CgkIqPj-8swdEAIQBQ"; // <GPGSID>
        public const string achievement_overachiever = "CgkIqPj-8swdEAIQCA"; // <GPGSID>
        public const string achievement_epic_launcher = "CgkIqPj-8swdEAIQAg"; // <GPGSID>
        public const string achievement_cratephobia = "CgkIqPj-8swdEAIQCQ"; // <GPGSID>
        public const string achievement_is_it_a_square = "CgkIqPj-8swdEAIQCw"; // <GPGSID>
        public const string achievement_novice_launcher = "CgkIqPj-8swdEAIQAA"; // <GPGSID>
        public const string achievement_low_hopes = "CgkIqPj-8swdEAIQCg"; // <GPGSID>
        public const string achievement_deep_space = "CgkIqPj-8swdEAIQBg"; // <GPGSID>
        public const string achievement_great_launcher = "CgkIqPj-8swdEAIQAQ"; // <GPGSID>
        public const string achievement_stormy_weather = "CgkIqPj-8swdEAIQBA"; // <GPGSID>
        public const string achievement_powerup_avoidance = "CgkIqPj-8swdEAIQBw"; // <GPGSID>
        public const string achievement_lifetime_launcher = "CgkIqPj-8swdEAIQAw"; // <GPGSID>

}
}
